import nodemailer from "nodemailer";

type AstroEmailProfile = {
  name: string;
  dateOfBirth: string;
  timeOfBirth: string;
  placeOfBirth: {
    name: string;
    displayName: string;
  };
};

function getRequiredEnv(
  name: string,
): string {
  const value =
    process.env[name]?.trim();

  if (!value) {
    throw new Error(
      `Missing environment variable: ${name}`,
    );
  }

  return value;
}

function escapeHtml(
  value: string,
): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

export async function sendAstroEmail({
  profile,
  question,
  answer,
}: {
  profile: AstroEmailProfile;
  question: string;
  answer: string;
}): Promise<void> {
  const gmailUser =
    getRequiredEnv(
      "GMAIL_USER",
    );

  const gmailPassword =
    getRequiredEnv(
      "GMAIL_APP_PASSWORD",
    );

  const gmailTo =
    getRequiredEnv(
      "GMAIL_TO",
    );

  const transporter =
    nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: gmailUser,
        pass: gmailPassword,
      },
    });

  const place =
    profile.placeOfBirth.displayName ||
    profile.placeOfBirth.name;

  const subject =
    `Name: ${profile.name}, ` +
    `DOB: ${profile.dateOfBirth}, ` +
    `Time of birth: ${profile.timeOfBirth}, ` +
    `Place: ${place}`;

  const safeQuestion =
    escapeHtml(question).replace(
      /\n/g,
      "<br />",
    );

  const safeAnswer =
    escapeHtml(answer).replace(
      /\n/g,
      "<br />",
    );

  const html = `
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>AstroAI</title>
  </head>

  <body
    style="
      margin: 0;
      padding: 24px;
      font-family: Arial, sans-serif;
      line-height: 1.6;
      color: #333333;
      background: #f7f5f0;
    "
  >
    <div
      style="
        max-width: 700px;
        margin: 0 auto;
        padding: 24px;
        background: #ffffff;
        border-radius: 12px;
      "
    >
      <h2>AstroAI New Question</h2>

      <h3>Birth Details</h3>

      <p>
        <strong>Name:</strong>
        ${escapeHtml(profile.name)}
      </p>

      <p>
        <strong>Date of Birth:</strong>
        ${escapeHtml(profile.dateOfBirth)}
      </p>

      <p>
        <strong>Time of Birth:</strong>
        ${escapeHtml(profile.timeOfBirth)}
      </p>

      <p>
        <strong>Place:</strong>
        ${escapeHtml(place)}
      </p>

      <hr />

      <h3>User Question</h3>

      <p>
        ${safeQuestion}
      </p>

      <hr />

      <h3>AstroAI Answer</h3>

      <div>
        ${safeAnswer}
      </div>

      <hr />

      <p
        style="
          color: #777777;
          font-size: 12px;
        "
      >
        Automatically generated by AstroAI.
      </p>
    </div>
  </body>
</html>
`;

  const text = `
AstroAI New Question

Birth Details
-------------
Name: ${profile.name}
Date of Birth: ${profile.dateOfBirth}
Time of Birth: ${profile.timeOfBirth}
Place: ${place}

User Question
-------------
${question}

AstroAI Answer
--------------
${answer}
`;

  await transporter.sendMail({
    from: `"AstroAI" <${gmailUser}>`,
    to: gmailTo,
    subject,
    text,
    html,
  });
}